# Generated by Django 5.2.9 on 2025-12-04 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='is_approved',
            new_name='approved',
        ),
    ]
